# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nfmelendez
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: truenorth
# "service" is the name of this project. This will also be added to your AWS resource names.
service: trueNorth

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"
      operationTableName: "operation-table-${sls:stage}"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [OperationTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    OPERATION_TABLE: ${param:operationTableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:tableName}
    OperationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: operation_id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: amount
            AttributeType: N
          - AttributeName: user_balance
            AttributeType: N
          - AttributeName: operation_response
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:operationTableName}
